(function mediaManager(){
  'use strict';
  const store=window.LEFUSIL_ADMIN_STORE,mount=document.querySelector('#mediaManager');
  if(!store||!mount)return;
  const $=(selector,root=document)=>root.querySelector(selector),$$=(selector,root=document)=>[...root.querySelectorAll(selector)];
  const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const supported=new Set(['jpg','jpeg','png','webp','avif','gif','svg']);
  const showroom=[
    ['assets/images/showroom/le-fusil-storefront.jpg','LE FUSIL storefront',['480','600']],
    ['assets/images/showroom/le-fusil-showroom-interior.jpg','LE FUSIL showroom interior',['640','1240']],
    ['assets/images/showroom/le-fusil-collection-wall.jpg','LE FUSIL collection wall',['640','1240']]
  ];
  const selected=new Set();let records=[],view='grid',current=null,returnFocus=null;
  const filename=path=>String(path).split('/').pop()||'';
  const extension=path=>(filename(path).split('.').pop()||'').toLowerCase();
  const external=path=>/^https?:\/\//i.test(path);
  function optimized(path,size){const parts=path.split('/'),file=parts.pop(),dot=file.lastIndexOf('.'),base=dot<0?file:file.slice(0,dot);return[...parts,'optimized',`${base}-${size}.webp`].join('/')}
  function inventory(){
    const products=store.getProducts(),physical=new Set(window.LEFUSIL_MEDIA_FILES||[]),map=new Map(),rawReferences=[];
    const ensure=path=>{if(!map.has(path))map.set(path,{path,filename:filename(path),extension:extension(path),usage:new Set(),products:[],brand:'',category:'',alt:'',exists:external(path)||physical.has(path),referenced:false});return map.get(path)};
    const addReference=(path,usage,product=null,alt='')=>{if(!path)return;const item=ensure(path);item.referenced=true;item.usage.add(usage);item.alt||=alt;if(product){item.brand||=product.brand||'';item.category||=product.category||'';if(!item.products.some(entry=>String(entry.id)===String(product.id)))item.products.push({id:product.id,name:product.name,brand:product.brand,category:product.category})}else{item.brand||='LE FUSIL';item.category||='Showroom'};rawReferences.push({path,usage,productId:product?.id||null,product:product?`${product.brand} ${product.name}`:'Showroom'})};
    products.forEach(product=>{const gallery=(product.gallery||[]).filter(path=>String(path||'').trim());gallery.forEach(path=>{addReference(path,'gallery',product,`${product.brand} ${product.name}`);addReference(optimized(path,'640'),'gallery',product,`${product.brand} ${product.name}`);addReference(optimized(path,'1600'),'gallery',product,`${product.brand} ${product.name}`)});if(product.image)addReference(product.image,'cover',product,`${product.brand} ${product.name}`)});
    showroom.forEach(([path,alt,sizes])=>{addReference(path,'showroom',null,alt);sizes.forEach(size=>addReference(optimized(path,size),'showroom',null,alt))});
    physical.forEach(path=>ensure(path));
    return {records:[...map.values()].map((item,index)=>({...item,id:`media-${index+1}`,usage:[...item.usage],brand:item.brand||'Unassigned',category:item.category||'Unassigned'})),references:rawReferences};
  }
  function rawValidation(){
    const products=store.getProducts(),raw=window.LEFUSIL_PRODUCTS||[],data=inventory(),galleryReferences=products.flatMap(product=>(product.gallery||[]).filter(path=>String(path||'').trim())),counts=galleryReferences.reduce((map,path)=>(map[path]=(map[path]||0)+1,map),{});
    const summary={missingImagePaths:data.records.filter(item=>item.referenced&&!item.exists&&!external(item.path)).length,emptyPaths:raw.reduce((count,product)=>count+(!String(product.image||'').trim()?1:0)+(product.gallery||[]).filter(path=>!String(path||'').trim()).length,0),duplicateReferences:Object.values(counts).filter(count=>count>1).length,unsupportedExtensions:data.records.filter(item=>item.referenced&&!supported.has(item.extension)).length,productsWithoutImages:products.filter(product=>!String(product.image||'').trim()&&!(product.gallery||[]).some(path=>String(path||'').trim())).length,unusedDiscoverableImages:data.records.filter(item=>item.exists&&!item.referenced).length};
    return {...summary,missingPaths:summary.missingImagePaths,duplicatePaths:summary.duplicateReferences,unsupportedExtension:summary.unsupportedExtensions,productsWithoutImage:summary.productsWithoutImages};
  }
  function validation(){const data=rawValidation();return{missingImagePaths:data.missingImagePaths,emptyPaths:data.emptyPaths,duplicateReferences:data.duplicateReferences,unsupportedExtensions:data.unsupportedExtensions,productsWithoutImages:data.productsWithoutImages,unusedDiscoverableImages:data.unusedDiscoverableImages}}
  function build(){
    records=inventory().records;
    const brands=[...new Set(records.filter(item=>item.referenced).map(item=>item.brand))].sort(),categories=[...new Set(records.filter(item=>item.referenced).map(item=>item.category))].sort(),products=[...new Set(records.flatMap(item=>item.products.map(product=>product.name)))].sort(),extensions=[...new Set(records.map(item=>item.extension))].sort();
    mount.innerHTML=`<div class="media-summary"><div><strong>${records.filter(item=>item.exists&&item.extension==='jpg'&&item.path.includes('/products/')).length}</strong><span>Catalog JPG</span></div><div><strong>${records.filter(item=>item.exists&&item.extension==='webp').length}</strong><span>WebP inventory</span></div><div><strong>${records.filter(item=>item.exists).length}</strong><span>Discovered assets</span></div><div><strong id="mediaSelectedCount">0</strong><span>Selected</span></div></div><form class="media-filters" id="mediaFilters"><label class="search-field"><span class="sr-only">Search media</span><input name="q" placeholder="Search filename, path or product…"></label>${select('brand','All brands',brands)}${select('category','All categories',categories)}${select('product','All products',products)}${select('extension','All extensions',extensions)}${select('usage','All usage types',['cover','gallery','showroom'])}${select('reference','Referenced or unused',['referenced','unused'])}${select('validity','Valid or missing',['valid','missing'])}<label><span class="sr-only">Sort media</span><select name="sort"><option value="az">Filename A–Z</option><option value="za">Filename Z–A</option><option value="path-asc">Path A–Z</option><option value="path-desc">Newest path</option></select></label><div class="media-view-toggle"><button type="button" data-media-view="grid" aria-label="Grid view" aria-pressed="true">▦</button><button type="button" data-media-view="list" aria-label="List view" aria-pressed="false">☷</button></div></form><div class="media-bulk"><button class="admin-button secondary" type="button" id="mediaSelectAll">Select All Visible</button><button class="admin-button secondary" type="button" id="mediaClearSelection">Clear Selection</button><button class="admin-button secondary" type="button" id="mediaCopySelected">Copy Selected Paths</button><button class="admin-button secondary" type="button" id="mediaExportSelected">Export Selected</button><button class="admin-button primary" type="button" id="mediaExport">Export JSON</button><span id="mediaResultCount"></span></div><div class="media-grid" id="mediaGrid"></div><section class="panel media-health"><div><p class="overline">Image Validation</p><h3>Media Health</h3></div><div id="mediaHealth"></div></section><section class="panel unused-panel"><p class="overline">Repository Review</p><h3>Images not referenced by any product</h3><div id="unusedImages"></div></section>`;
    bind();render();
  }
  function select(name,label,values){return`<label><span class="sr-only">${label}</span><select name="${name}"><option value="">${label}</option>${values.map(value=>`<option value="${esc(value)}">${esc(value)}</option>`).join('')}</select></label>`}
  function filtered(){
    const data=new FormData($('#mediaFilters')),q=String(data.get('q')||'').toLowerCase(),brand=data.get('brand'),category=data.get('category'),product=data.get('product'),ext=data.get('extension'),usage=data.get('usage'),reference=data.get('reference'),validity=data.get('validity');
    const matchReference=item=>!reference||(reference==='referenced'?item.referenced:!item.referenced),matchValidity=item=>!validity||(validity==='valid'?item.exists:!item.exists);
    const list=records.filter(item=>(!q||[item.filename,item.path,...item.products.map(entry=>`${entry.brand} ${entry.name}`)].join(' ').toLowerCase().includes(q))&&(!brand||item.brand===brand)&&(!category||item.category===category)&&(!product||item.products.some(entry=>entry.name===product))&&(!ext||item.extension===ext)&&(!usage||item.usage.includes(usage))&&matchReference(item)&&matchValidity(item));
    const sort=data.get('sort');list.sort(sort==='path-desc'?(a,b)=>b.path.localeCompare(a.path):sort==='path-asc'?(a,b)=>a.path.localeCompare(b.path):sort==='za'?(a,b)=>b.filename.localeCompare(a.filename):(a,b)=>a.filename.localeCompare(b.filename));return list;
  }
  function card(item){const product=item.products[0],checked=selected.has(item.path),owner=product?`${product.brand} · ${product.name}`:(item.referenced?'LE FUSIL showroom':'Unused repository asset');return`<article class="media-card${checked?' selected':''}${item.exists?'':' missing'}" data-media-path="${esc(item.path)}"><label class="media-select"><input type="checkbox" ${checked?'checked':''} aria-label="Select ${esc(item.filename)}"><span></span></label><button class="media-open" type="button" aria-label="View details for ${esc(item.filename)}"><span class="media-thumb">${item.exists?`<img src="${esc(item.path)}" alt="" loading="lazy" decoding="async">`:'<span class="media-missing">Missing</span>'}</span><span class="media-card-copy"><strong>${esc(item.filename)}</strong><small>${esc(owner)}</small><code>${esc(item.path)}</code><span><em>${esc(item.extension||'none')}</em>${item.usage.map(type=>`<em>${esc(type)}</em>`).join('')}</span></span></button></article>`}
  function render(){const list=filtered(),grid=$('#mediaGrid');grid.className=`media-grid ${view==='list'?'media-list':''}`;grid.innerHTML=list.map(card).join('');$('#mediaResultCount').textContent=`${list.length} assets`;$('#mediaSelectedCount').textContent=selected.size;$$('[data-media-view]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.mediaView===view)));renderHealth()}
  function renderHealth(){const summary=validation();$('#mediaHealth').innerHTML=Object.entries(summary).map(([key,value])=>`<div class="health-row"><span>${esc(key.replace(/([A-Z])/g,' $1'))}</span><strong class="health-count ${value?'issue':'good'}">${value||'Clear'}</strong></div>`).join('');const unused=records.filter(item=>item.exists&&!item.referenced);$('#unusedImages').innerHTML=unused.length?unused.map(item=>`<button type="button" class="unused-image" data-unused-path="${esc(item.path)}">${esc(item.path)}</button>`).join(''):'<p class="panel-note">No unreferenced discoverable images were found.</p>'}
  function bind(){
    const filters=$('#mediaFilters');filters.addEventListener('input',render);$$('[data-media-view]').forEach(button=>button.addEventListener('click',()=>{view=button.dataset.mediaView;render()}));
    $('#mediaGrid').addEventListener('change',event=>{const checkbox=event.target.closest('.media-select input');if(!checkbox)return;const path=checkbox.closest('[data-media-path]').dataset.mediaPath;checkbox.checked?selected.add(path):selected.delete(path);render()});
    $('#mediaGrid').addEventListener('click',event=>{const button=event.target.closest('.media-open');if(button)openDetails(records.find(item=>item.path===button.closest('[data-media-path]').dataset.mediaPath),button)});
    $('#mediaSelectAll').addEventListener('click',()=>{filtered().forEach(item=>selected.add(item.path));render()});$('#mediaClearSelection').addEventListener('click',()=>{selected.clear();render()});$('#mediaCopySelected').addEventListener('click',()=>copy([...selected].join('\n'),'Selected image paths copied.'));$('#mediaExportSelected').addEventListener('click',()=>exportInventory(records.filter(item=>selected.has(item.path)),'selected'));$('#mediaExport').addEventListener('click',()=>exportInventory(records,'inventory'));$('#unusedImages').addEventListener('click',event=>{const button=event.target.closest('[data-unused-path]');if(button)openDetails(records.find(item=>item.path===button.dataset.unusedPath),button)});
  }
  function openDetails(item,opener){if(!item)return;current=item;returnFocus=opener;const modal=$('#mediaModal'),details=$('#mediaDetails'),products=item.products.map(product=>`${product.brand} ${product.name}`).join(', ')||(item.referenced?'Showroom asset':'Not referenced');details.innerHTML=`<div class="media-detail-layout"><div class="media-preview">${item.exists?`<img id="mediaPreviewImage" src="${esc(item.path)}" alt="${esc(item.alt)}">`:'<p class="media-missing">Image file is missing.</p>'}</div><div class="media-meta"><p class="overline">${esc((item.extension||'No extension').toUpperCase())} · ${esc(item.usage.join(', ')||'unused')}</p><h3>${esc(item.filename||'Empty path')}</h3><dl><dt>Image path</dt><dd><code>${esc(item.path||'Empty')}</code></dd><dt>Extension</dt><dd>${esc(item.extension||'None')}</dd><dt>Natural dimensions</dt><dd id="mediaDimensions">${item.exists?'Reading image…':'Unavailable'}</dd><dt>Products using image</dt><dd>${esc(products)}</dd></dl><div class="button-row"><button class="admin-button secondary" type="button" data-copy-path>Copy Path</button><button class="admin-button secondary" type="button" data-copy-filename>Copy Filename</button></div><section class="media-replace"><h4>Replace Image</h4><p class="media-storage-warning">Permanent image uploads require backend storage.</p><label>Existing path or external URL<input id="mediaReplacement" value="${esc(item.path)}"></label><label class="file-field">Temporary local preview<input type="file" id="mediaLocalPreview" accept="image/*"></label><button class="admin-button primary" type="button" id="applyMediaReplacement" ${item.products.length?'':'disabled'}>Apply Demo Override</button></section></div></div>`;$('#mediaModalTitle').textContent=item.filename||'Image details';modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';const image=$('#mediaPreviewImage');if(image){image.addEventListener('load',()=>$('#mediaDimensions').textContent=`${image.naturalWidth} × ${image.naturalHeight} px`);image.addEventListener('error',()=>$('#mediaDimensions').textContent='Unavailable')}details.addEventListener('click',detailAction);$('#mediaLocalPreview').addEventListener('change',localPreview);setTimeout(()=>$('[data-media-close]').focus(),30)}
  function detailAction(event){if(event.target.closest('[data-copy-path]'))copy(current.path,'Image path copied.');if(event.target.closest('[data-copy-filename]'))copy(current.filename,'Filename copied.');if(event.target.closest('#applyMediaReplacement'))replaceImage()}
  function localPreview(event){const file=event.target.files[0];if(!file)return;const image=$('#mediaPreviewImage');if(!image)return;const url=URL.createObjectURL(file);image.src=url;$('#mediaDimensions').textContent='Temporary local preview — not uploaded or persisted.'}
  function replaceImage(){const path=$('#mediaReplacement').value.trim();if(!path){notify('Enter an existing path or external URL.');return}if(!/^(https?:\/\/|assets\/)/i.test(path)){notify('Use an assets/ path or an http(s) URL.');return}current.products.forEach(reference=>{const product=store.getProduct(reference.id),gallery=(product.gallery||[]).map(item=>item===current.path?path:item),updates={gallery};if(product.image===current.path)updates.image=path;store.updateProduct(product.id,updates)});store.addAuditEvent('replace image','A browser-local media path override was applied.');notify('Demo image override saved locally.');closeDetails();build()}
  function closeDetails(){const modal=$('#mediaModal');modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow='';current=null;returnFocus?.focus()}
  function copy(text,message){if(!text){notify('No image paths selected.');return}navigator.clipboard.writeText(text).then(()=>notify(message)).catch(()=>notify('Clipboard access is unavailable.'))}
  function exportInventory(items,label){if(!items.length){notify('No images selected for export.');return}const data=inventory(),included=new Set(items.map(item=>item.path)),payload={schemaVersion:1,exportedAt:new Date().toISOString(),inventory:items.map(item=>({path:item.path,filename:item.filename,extension:item.extension,usage:item.usage,referenced:item.referenced,valid:item.exists,products:item.products})),references:data.references.filter(reference=>included.has(reference.path)),validationSummary:validation()},blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`lefusil-media-${label}-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(url);store.addAuditEvent('export media',`${items.length} media records exported.`)}
  function notify(message){const status=$('#adminStatus');status.textContent=message;status.classList.add('show');setTimeout(()=>status.classList.remove('show'),3000)}
  $$('[data-media-close]').forEach(button=>button.addEventListener('click',closeDetails));document.addEventListener('keydown',event=>{if(!$('#mediaModal').classList.contains('open'))return;if(event.key==='Escape'){event.preventDefault();event.stopImmediatePropagation();closeDetails();return}if(event.key==='Tab'){const items=$$('button:not([disabled]),input:not([disabled])',$('#mediaModal')).filter(item=>item.offsetParent!==null),first=items[0],last=items.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();event.stopImmediatePropagation();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();event.stopImmediatePropagation();first.focus()}}},true);
  window.LEFUSIL_MEDIA={render:()=>{if(!records.length)build();else render()},getInventory:()=>inventory().records,getValidation:()=>rawValidation()};
})();
