(function adminDashboard(){
  'use strict';
  const store=window.LEFUSIL_ADMIN_STORE;
  if(!store)return;
  const $=(selector,root=document)=>root.querySelector(selector),$$=(selector,root=document)=>[...root.querySelectorAll(selector)];
  const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const money=value=>Number(value)>0?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(value):'Price on Request';
  const sessionKey=store.KEYS.session;
  let currentView='overview',page=1,pendingImport=null,returnFocus=null,confirmCallback=null,statusTimer;
  const app=$('#adminApp'),access=$('#accessScreen'),productModal=$('#productModal'),confirmModal=$('#confirmModal');
  function announce(message){const status=$('#adminStatus');status.textContent=message;status.classList.add('show');clearTimeout(statusTimer);statusTimer=setTimeout(()=>status.classList.remove('show'),3200)}
  function isSession(){return sessionStorage.getItem(sessionKey)==='true'||localStorage.getItem(sessionKey)==='true'}
  function setSession(remember){(remember?localStorage:sessionStorage).setItem(sessionKey,'true')}
  function clearSession(){localStorage.removeItem(sessionKey);sessionStorage.removeItem(sessionKey)}
  function showApp(){access.hidden=true;app.hidden=false;renderAll();$('#adminMain').focus()}
  function showLogin(){app.hidden=true;access.hidden=false;setTimeout(()=>$('#loginForm [name=email]').focus(),30)}
  $('#loginForm').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form),email=String(data.get('email')).trim(),password=String(data.get('password'));if(email!=='admin@lefusil.demo'||password!=='LEFUSIL-DEMO'){$('#loginMessage').textContent='Incorrect demonstration credentials.';form.elements.password.value='';form.elements.password.focus();return}setSession(data.get('remember')==='on');store.audit('login','Demonstration session started.');form.reset();$('#loginMessage').textContent='';showApp()});
  $('#logoutButton').addEventListener('click',()=>{store.audit('logout','Demonstration session ended.');clearSession();closeSidebar();showLogin()});
  function switchView(view){currentView=view;$$('[data-panel]').forEach(panel=>panel.classList.toggle('active',panel.dataset.panel===view));$$('[data-view]').forEach(button=>button.classList.toggle('active',button.dataset.view===view));const labels={overview:['Dashboard','Overview'],products:['Catalog Management','Products'],media:['Catalog Assets','Media Library'],inquiries:['Private Requests','Inquiries'],crm:['Client Relationships','Customer CRM'],settings:['Admin Preview','Collection Settings'],transfer:['Portability','Import / Export']};$('#viewEyebrow').textContent=labels[view][0];$('#viewTitle').textContent=labels[view][1];$('#addProduct').hidden=view!=='products';closeSidebar();$(`[data-panel="${view}"]`).focus?.();if(view==='products')renderProducts();if(view==='media')window.LEFUSIL_MEDIA?.render();if(view==='crm')window.LEFUSIL_CRM?.render();if(view==='inquiries')renderInquiries();if(view==='overview')renderOverview()}
  $$('[data-view]').forEach(button=>button.addEventListener('click',()=>switchView(button.dataset.view)));
  const sidebar=$('#adminSidebar'),drawer=$('#drawerBackdrop'),menuButton=$('#openSidebar');
  function openSidebar(){returnFocus=document.activeElement;sidebar.classList.add('open');drawer.hidden=false;document.body.style.overflow='hidden';menuButton.setAttribute('aria-expanded','true');setTimeout(()=>$('#closeSidebar').focus(),30)}
  function closeSidebar(){sidebar.classList.remove('open');drawer.hidden=true;document.body.style.overflow='';menuButton.setAttribute('aria-expanded','false');if(returnFocus&&matchMedia('(max-width:900px)').matches)returnFocus.focus()}
  menuButton.addEventListener('click',openSidebar);$('#closeSidebar').addEventListener('click',closeSidebar);drawer.addEventListener('click',closeSidebar);
  function focusables(layer){return $$('button:not([disabled]),a[href],input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])',layer).filter(el=>el.offsetParent!==null)}
  function trap(event,layer){if(event.key!=='Tab')return;const items=focusables(layer);if(!items.length)return;const first=items[0],last=items.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}
  document.addEventListener('keydown',event=>{const modal=$('.modal.open');if(event.key==='Escape'){if(modal){event.preventDefault();closeModal(modal)}else if(sidebar.classList.contains('open'))closeSidebar()}if(modal)trap(event,modal);else if(sidebar.classList.contains('open'))trap(event,sidebar)});
  function openModal(modal,opener){returnFocus=opener||document.activeElement;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';setTimeout(()=>focusables(modal)[0]?.focus(),30)}
  function closeModal(modal){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow='';returnFocus?.focus()}
  $$('[data-close-modal]').forEach(button=>button.addEventListener('click',()=>closeModal(productModal)));
  $$('[data-confirm-cancel]').forEach(button=>button.addEventListener('click',()=>closeModal(confirmModal)));
  function confirmAction(title,message,callback,opener){$('#confirmTitle').textContent=title;$('#confirmMessage').textContent=message;confirmCallback=callback;openModal(confirmModal,opener)}
  $('#confirmAction').addEventListener('click',()=>{const callback=confirmCallback;closeModal(confirmModal);confirmCallback=null;callback?.()});
  function catalogHealth(products){
    const duplicate=key=>{
      const seen=new Set(),duplicates=new Set();
      products.forEach(item=>{const value=String(item[key]||'').toLowerCase();if(!value)return;if(seen.has(value))duplicates.add(value);else seen.add(value)});
      return duplicates.size;
    };
    const paths=products.flatMap(item=>item.gallery||[]),pathCounts=paths.reduce((map,path)=>(path&&(map[path]=(map[path]||0)+1),map),{}),unsupported=paths.filter(path=>path&&!/\.(jpe?g|png|webp|avif|gif|svg)$/i.test(path)).length,empty=(window.LEFUSIL_PRODUCTS||[]).reduce((count,item)=>count+(item.image===''?1:0)+(item.gallery||[]).filter(path=>!String(path).trim()).length,0);
    return[{label:'Products without an image',count:products.filter(item=>!item.image&&!item.gallery?.length).length},{label:'Missing image paths',count:window.LEFUSIL_MEDIA?.getValidation().missingPaths||0},{label:'Duplicate image paths',count:Object.values(pathCounts).filter(count=>count>1).length},{label:'Empty image paths',count:empty},{label:'Unsupported image extension',count:unsupported},{label:'Products without a numeric price',count:products.filter(item=>!(Number(item.price)>0)).length},{label:'Products without SKU',count:products.filter(item=>!item.sku).length},{label:'Products without category',count:products.filter(item=>!item.category).length},{label:'Products without description',count:products.filter(item=>!item.description).length},{label:'Duplicate slugs',count:duplicate('slug')},{label:'Duplicate SKUs',count:duplicate('sku')}];
  }
  function renderOverview(){const products=store.getProducts(),inquiries=store.getInquiries(),metrics=[['Total Products',products.length],['Published',products.filter(item=>item.status==='Published').length],['Draft',products.filter(item=>item.status==='Draft').length],['Archived',products.filter(item=>item.status==='Archived').length],['Numeric Prices',products.filter(item=>Number(item.price)>0&&!item.priceOnRequest).length],['Price on Request',products.filter(item=>item.priceOnRequest||!(Number(item.price)>0)).length],['Featured Products',products.filter(item=>item.featured).length],['Demo-created',products.filter(item=>item.createdByAdminDemo).length],['Saved Inquiries',inquiries.length]];$('#metrics').innerHTML=metrics.map(([label,value])=>`<article class="metric"><span>${escapeHtml(label)}</span><strong>${value}</strong></article>`).join('');$('#healthChecks').innerHTML=catalogHealth(products).map(check=>`<div class="health-row"><span>${escapeHtml(check.label)}</span><strong class="health-count ${check.count?'issue':'good'}">${check.count||'Clear'}</strong></div>`).join('');const audit=store.getAuditLog().slice(0,20);$('#auditLog').innerHTML=audit.length?audit.map(item=>`<div class="audit-row"><div><p>${escapeHtml(item.type||item.action)}</p><small>${escapeHtml(item.detail)}</small></div><small>${new Date(item.timestamp||item.createdAt).toLocaleString()}</small></div>`).join(''):'<div class="empty-state">No local activity recorded yet.</div>';$('#inquiryNavCount').textContent=inquiries.filter(item=>item.status==='New').length}
  function populateFilters(products){const add=(name,values)=>{const select=$(`#productFilters [name="${name}"]`),current=select.value,first=select.options[0].outerHTML;select.innerHTML=first+[...new Set(values.filter(Boolean))].sort().map(value=>`<option>${escapeHtml(value)}</option>`).join('');select.value=current};add('brand',products.map(item=>item.brand));add('category',products.map(item=>item.category))}
  function filteredProducts(){const products=store.getProducts(),data=new FormData($('#productFilters')),q=String(data.get('q')||'').toLowerCase(),brand=data.get('brand'),category=data.get('category'),status=data.get('status'),price=data.get('price'),featured=data.get('featured'),sort=data.get('sort');let list=products.filter(item=>(!q||[item.name,item.brand,item.sku,item.slug].join(' ').toLowerCase().includes(q))&&(!brand||item.brand===brand)&&(!category||item.category===category)&&(!status||item.status===status)&&(!featured||String(item.featured)===featured)&&(!price||(price==='numeric'?!item.priceOnRequest&&Number(item.price)>0:item.priceOnRequest||!(Number(item.price)>0))));if(sort==='brand')list.sort((a,b)=>a.brand.localeCompare(b.brand)||a.name.localeCompare(b.name));else if(sort==='price-desc')list.sort((a,b)=>(Number(b.price)||-1)-(Number(a.price)||-1));else if(sort==='updated')list.sort((a,b)=>String(b.updatedAt||'').localeCompare(String(a.updatedAt||'')));else list.sort((a,b)=>a.name.localeCompare(b.name));return list}
  function actions(item){return `<div class="row-actions"><a href="product.html?slug=${encodeURIComponent(item.slug)}" target="_blank" rel="noopener" title="View product" aria-label="View ${escapeHtml(item.name)}">↗</a><button type="button" data-action="edit" data-id="${escapeHtml(item.id)}" title="Edit" aria-label="Edit ${escapeHtml(item.name)}">✎</button><button type="button" data-action="duplicate" data-id="${escapeHtml(item.id)}" title="Duplicate as demo" aria-label="Duplicate ${escapeHtml(item.name)} as demo">⧉</button><button type="button" data-action="${item.status==='Archived'?'restore':'archive'}" data-id="${escapeHtml(item.id)}" title="${item.status==='Archived'?'Restore':'Archive'}" aria-label="${item.status==='Archived'?'Restore':'Archive'} ${escapeHtml(item.name)}">${item.status==='Archived'?'↺':'—'}</button>${item.createdByAdminDemo?`<button type="button" data-action="delete" data-id="${escapeHtml(item.id)}" title="Delete demo product" aria-label="Delete demo product ${escapeHtml(item.name)}">×</button>`:''}</div>`}
  function renderProducts(){const all=store.getProducts();populateFilters(all);const list=filteredProducts(),pageSize=Number($('#pageSize').value),pages=Math.max(1,Math.ceil(list.length/pageSize));page=Math.min(page,pages);const shown=list.slice((page-1)*pageSize,page*pageSize);$('#productCount').textContent=`${list.length} result${list.length===1?'':'s'} · page ${page} of ${pages}`;$('#productRows').innerHTML=shown.map(item=>`<tr><td><div class="product-piece">${item.image?`<img src="${escapeHtml(item.image)}" alt="">`:'<span></span>'}<div><strong>${escapeHtml(item.name)}</strong><small>${escapeHtml(item.brand)}</small></div></div></td><td><strong>${escapeHtml(item.sku)}</strong><div class="table-meta">${escapeHtml(item.slug)}</div></td><td>${escapeHtml(item.category)}</td><td>${money(item.priceOnRequest?null:item.price)}</td><td><span class="status-badge ${escapeHtml(item.status)}">${escapeHtml(item.status)}</span></td><td><span class="featured-mark">${item.featured?'◆':'—'}</span></td><td>${actions(item)}</td></tr>`).join('');$('#mobileProductList').innerHTML=shown.map(item=>`<article class="mobile-product-card">${item.image?`<img src="${escapeHtml(item.image)}" alt="">`:'<span></span>'}<div><h3>${escapeHtml(item.name)}</h3><p>${escapeHtml(item.brand)} · ${escapeHtml(item.sku)}</p><p>${money(item.priceOnRequest?null:item.price)} · ${escapeHtml(item.status)}</p></div>${actions(item)}</article>`).join('');$('#pagination').innerHTML=Array.from({length:pages},(_,index)=>`<button type="button" data-page="${index+1}" ${page===index+1?'aria-current="page"':''} aria-label="Page ${index+1}">${index+1}</button>`).join('')}
  $('#productFilters').addEventListener('input',()=>{page=1;renderProducts()});$('#productFilters').addEventListener('reset',()=>setTimeout(()=>{page=1;renderProducts()}));$('#pageSize').addEventListener('change',()=>{page=1;renderProducts()});$('#pagination').addEventListener('click',event=>{const button=event.target.closest('[data-page]');if(button){page=Number(button.dataset.page);renderProducts();scrollTo({top:0,behavior:'smooth'})}});
  function slugify(value){return String(value).toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
  function addSpec(key='',value=''){const row=document.createElement('div');row.className='spec-row';row.innerHTML=`<input aria-label="Specification name" placeholder="Specification" value="${escapeHtml(key)}"><input aria-label="Specification value" placeholder="Value" value="${escapeHtml(value)}"><button class="remove-row" type="button" aria-label="Remove specification">×</button>`;$('#specificationRows').append(row)}
  function addImage(path=''){const row=document.createElement('div');row.className='image-row';row.innerHTML=`${path?`<img src="${escapeHtml(path)}" alt="">`:'<span></span>'}<input aria-label="Image path" placeholder="assets/images/…" value="${escapeHtml(path)}"><button class="move-row" data-direction="up" type="button" aria-label="Move image up">↑</button><button class="move-row" data-direction="down" type="button" aria-label="Move image down">↓</button><button class="remove-row" type="button" aria-label="Remove image">×</button>`;$('#imageRows').append(row)}
  $('#addSpecification').addEventListener('click',()=>addSpec());$('#addImage').addEventListener('click',()=>addImage());
  $('#specificationRows').addEventListener('click',event=>event.target.closest('.remove-row')?.closest('.spec-row').remove());
  $('#imageRows').addEventListener('click',event=>{const remove=event.target.closest('.remove-row'),move=event.target.closest('.move-row'),row=event.target.closest('.image-row');if(remove)row.remove();if(move){const sibling=move.dataset.direction==='up'?row.previousElementSibling:row.nextElementSibling;if(sibling)row.parentNode.insertBefore(move.dataset.direction==='up'?row:sibling,move.dataset.direction==='up'?sibling:row)}});
  $('#imagePreview').addEventListener('change',event=>{const file=event.target.files[0];if(!file)return;const url=URL.createObjectURL(file);$('#localImagePreview').innerHTML=`<img src="${url}" alt="Local image preview"><p>Preview only. This file is not uploaded or stored.</p>`});
  function openEditor(item=null,opener){const form=$('#productForm'),field=form.elements;form.reset();$('#formErrors').className='form-errors';$('#formErrors').textContent='';$('#specificationRows').innerHTML='';$('#imageRows').innerHTML='';$('#localImagePreview').innerHTML='';$('#editorTitle').textContent=item?'Edit Product':'Add Demo Product';field.id.value=item?.id||'';field.name.value=item?.name||'';field.brand.value=item?.brand||'';field.model.value=item?.model||'';field.sku.value=item?.sku||'';field.slug.value=item?.slug||'';field.category.value=item?.category||'';field.calibre.value=item?.calibre||'';field.price.value=item?.price||'';field.priceOnRequest.checked=item?item.priceOnRequest:true;field.description.value=item?.description||'';field.status.value=item?.status||'Draft';field.featured.checked=Boolean(item?.featured);Object.entries(item?.specifications||{}).forEach(([key,value])=>addSpec(key,value));(item?.gallery||[]).forEach(addImage);if(!item)addImage();openModal(productModal,opener)}
  $('#addProduct').addEventListener('click',event=>openEditor(null,event.currentTarget));
  $('#productForm [name=name]').addEventListener('input',event=>{const field=$('#productForm').elements;if(!field.id.value&&!field.slug.value)field.slug.value=slugify(event.target.value)});
  function editorData(){const form=$('#productForm'),field=form.elements,specifications={},gallery=[];$$('#specificationRows .spec-row').forEach(row=>{const inputs=$$('input',row),key=inputs[0].value.trim(),value=inputs[1].value.trim();if(key)specifications[key]=value});$$('#imageRows .image-row input').forEach(input=>{const path=input.value.trim();if(path)gallery.push(path)});const request=field.priceOnRequest.checked;return{id:field.id.value,name:field.name.value.trim(),brand:field.brand.value.trim(),model:field.model.value.trim(),sku:field.sku.value.trim(),slug:field.slug.value.trim(),category:field.category.value.trim(),calibre:field.calibre.value.trim(),price:request?null:Number(field.price.value),priceOnRequest:request,description:field.description.value.trim(),shortDescription:field.description.value.trim(),status:field.status.value,featured:field.featured.checked,specifications,gallery,image:gallery[0]||''}}
  function validateProduct(data){const errors=[],products=store.getProducts(),other=products.filter(item=>String(item.id)!==String(data.id));if(!data.name)errors.push('Product name is required.');if(!data.brand)errors.push('Brand is required.');if(!data.sku)errors.push('SKU is required.');if(!data.slug)errors.push('Slug is required.');else if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(data.slug))errors.push('Slug may contain lowercase letters, numbers and hyphens only.');if(data.slug&&other.some(item=>item.slug.toLowerCase()===data.slug.toLowerCase()))errors.push('Slug must be unique.');if(data.sku&&other.some(item=>item.sku.toLowerCase()===data.sku.toLowerCase()))errors.push('SKU must be unique.');if(!data.priceOnRequest&&!(data.price>0))errors.push('Enter a price greater than zero or select Price on Request.');if(data.status==='Published'&&!data.gallery.length)errors.push('Published products require at least one image path.');return errors}
  $('#productForm').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget,data=editorData(),errors=validateProduct(data),box=$('#formErrors');$$('[aria-invalid="true"]',form).forEach(field=>{field.removeAttribute('aria-invalid');field.removeAttribute('aria-describedby')});if(errors.length){box.className='form-errors show';box.innerHTML=errors.map(error=>`<div>${escapeHtml(error)}</div>`).join('');const fieldName=errors[0].toLowerCase().includes('brand')?'brand':errors[0].toLowerCase().includes('sku')?'sku':errors[0].toLowerCase().includes('slug')?'slug':errors[0].toLowerCase().includes('price')?'price':'name',field=form.elements[fieldName];field?.setAttribute('aria-invalid','true');field?.setAttribute('aria-describedby','formErrors');field?.focus();return}if(data.id)store.updateProduct(data.id,data);else store.createProduct(data);closeModal(productModal);renderAll();announce(data.id?'Product override saved locally.':'Demo product created locally.')});
  $('#previewProduct').addEventListener('click',()=>{const data=editorData(),errors=validateProduct({...data,status:'Draft'});if(errors.filter(error=>!error.includes('image')).length){$('#formErrors').className='form-errors show';$('#formErrors').textContent=errors[0];return}const win=open('','_blank','noopener,noreferrer');if(!win){announce('Preview window was blocked.');return}win.document.write(`<!doctype html><title>Demo Preview</title><style>body{margin:0;background:#171815;color:#eee;font-family:Arial;padding:8vw}small{color:#b08a50;text-transform:uppercase;letter-spacing:.18em}h1{font:4rem Georgia;margin:.3em 0}.price{font:1.5rem Georgia}p{max-width:700px;line-height:1.7}</style><small>Local demo preview · ${escapeHtml(data.brand)}</small><h1>${escapeHtml(data.name)}</h1><p class="price">${money(data.priceOnRequest?null:data.price)}</p><p>${escapeHtml(data.description||'No description provided.')}</p>`);win.document.close()});
  function duplicate(item){store.duplicateProduct(item.id);renderAll();announce('Demo copy created as Draft.')}
  function handleProductAction(event){const button=event.target.closest('[data-action]');if(!button)return;const item=store.getProduct(button.dataset.id);if(!item)return;if(button.dataset.action==='edit')openEditor(item,button);if(button.dataset.action==='duplicate')duplicate(item);if(button.dataset.action==='archive')confirmAction('Archive product',`Hide ${item.brand} ${item.name} from the active demo catalog?`,()=>{store.archiveProduct(item.id);renderAll();announce('Product archived locally.')},button);if(button.dataset.action==='restore'){store.restoreProduct(item.id);renderAll();announce('Product restored locally.')}if(button.dataset.action==='delete')confirmAction('Delete demo product',`Permanently remove the browser-local demo product ${item.brand} ${item.name}?`,()=>{store.deleteDemoProduct(item.id);renderAll();announce('Demo product deleted.')},button)}
  $('#productRows').addEventListener('click',handleProductAction);$('#mobileProductList').addEventListener('click',handleProductAction);
  function renderInquiries(){const items=store.getInquiries();$('#inquiryNavCount').textContent=items.filter(item=>item.status==='New').length;$('#inquiryList').innerHTML=items.length?items.map(item=>`<article class="inquiry-card"><div><h3>${escapeHtml(item.name||'Unnamed inquiry')}</h3><p>${escapeHtml(item.productName||'General inquiry')}</p><p>${escapeHtml(item.message)}</p><small>${new Date(item.createdAt).toLocaleString()}</small></div><div>${item.email?`<p><a href="mailto:${encodeURIComponent(item.email)}">${escapeHtml(item.email)}</a></p>`:''}${item.phone?`<p><a href="tel:${escapeHtml(item.phone)}">${escapeHtml(item.phone)}</a></p>`:''}<label><span class="sr-only">Inquiry status</span><select class="inquiry-status" data-inquiry-status="${escapeHtml(item.id)}">${['New','Contacted','Appointment Scheduled','Closed','Archived'].map(status=>`<option ${item.status===status?'selected':''}>${status}</option>`).join('')}</select></label></div><div class="inquiry-actions"><button type="button" data-copy-inquiry="${escapeHtml(item.id)}" aria-label="Copy inquiry summary" title="Copy summary">⧉</button><button type="button" data-archive-inquiry="${escapeHtml(item.id)}" aria-label="Archive inquiry" title="Archive">—</button><button type="button" data-delete-inquiry="${escapeHtml(item.id)}" aria-label="Delete demo inquiry" title="Delete">×</button></div></article>`).join(''):'<div class="panel empty-state">No demonstration inquiries have been saved in this browser.</div>'}
  $('#inquiryList').addEventListener('change',event=>{const select=event.target.closest('[data-inquiry-status]');if(select){store.updateInquiryStatus(select.dataset.inquiryStatus,select.value);renderOverview();announce('Inquiry status updated locally.')}});$('#inquiryList').addEventListener('click',async event=>{const copy=event.target.closest('[data-copy-inquiry]'),archive=event.target.closest('[data-archive-inquiry]'),remove=event.target.closest('[data-delete-inquiry]');if(copy){const item=store.getInquiries().find(entry=>entry.id===copy.dataset.copyInquiry),summary=[item.name,item.email,item.phone,item.productName,item.message].filter(Boolean).join('\n');await navigator.clipboard.writeText(summary);announce('Inquiry summary copied.')}if(archive){store.archiveInquiry(archive.dataset.archiveInquiry);renderAll();announce('Inquiry archived.')}if(remove)confirmAction('Delete demo inquiry','Remove this local demonstration inquiry?',()=>{store.deleteInquiry(remove.dataset.deleteInquiry);renderAll();announce('Demo inquiry deleted.')},remove)});
  function syncInquiryFilters(){const form=$('#inquiryFilters');if(!form)return;const select=form.elements.product,current=select.value,names=[...new Set(store.getInquiries().map(item=>item.productName).filter(Boolean))].sort();select.innerHTML='<option value="">All products</option>'+names.map(name=>`<option>${escapeHtml(name)}</option>`).join('');select.value=current;applyInquiryFilters()}
  function applyInquiryFilters(){const form=$('#inquiryFilters');if(!form)return;const data=new FormData(form),q=String(data.get('q')||'').toLowerCase(),status=data.get('status'),product=String(data.get('product')||'').toLowerCase(),list=$('#inquiryList'),cards=$$('.inquiry-card',list);cards.forEach(card=>{const cardStatus=$('.inquiry-status',card)?.value||'',text=card.textContent.toLowerCase();card.hidden=Boolean((q&&!text.includes(q))||(status&&cardStatus!==status)||(product&&!text.includes(product)))});if(data.get('sort')==='oldest')cards.reverse().forEach(card=>list.append(card))}
  $('#inquiryFilters').addEventListener('input',applyInquiryFilters);$('#inquiryFilters').addEventListener('reset',()=>setTimeout(applyInquiryFilters));
  function renderSettings(){const settings=store.getSettings(),form=$('#settingsForm');form.showFeatured.checked=settings.showFeatured;form.featuredIds.value=settings.featuredIds.join(', ');form.defaultSort.value=settings.defaultSort;form.perPage.value=settings.perPage;form.showPrices.checked=settings.showPrices;form.showRequestLabel.checked=settings.showRequestLabel;form.showArchived.checked=settings.showArchived;form.density.value=settings.density;const enabled=localStorage.getItem(store.KEYS.preview)==='true';$('#togglePreview').textContent=enabled?'Exit Preview':'Enable Local Website Preview';$('#togglePreview').classList.toggle('danger',enabled)}
  $('#settingsForm').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;store.saveSettings({showFeatured:form.showFeatured.checked,featuredIds:form.featuredIds.value.split(',').map(value=>value.trim()).filter(Boolean),defaultSort:form.defaultSort.value,perPage:Number(form.perPage.value),showPrices:form.showPrices.checked,showRequestLabel:form.showRequestLabel.checked,showArchived:form.showArchived.checked,density:form.density.value});announce('Demo admin settings saved locally.');renderAll()});
  $('#togglePreview').addEventListener('click',()=>{const enabled=localStorage.getItem(store.KEYS.preview)==='true';localStorage.setItem(store.KEYS.preview,String(!enabled));store.addAuditEvent(!enabled?'preview enable':'preview disable','Browser-local preview preference changed.');renderSettings();announce(!enabled?'Local preview flag enabled. Public renderers remain unchanged.':'Local preview flag disabled.')});
  function exportText(){return JSON.stringify(store.exportData(),null,2)}
  $('#downloadExport').addEventListener('click',()=>{const blob=new Blob([exportText()],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`lefusil-admin-demo-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(url);announce('Demo export downloaded.')});
  $('#copyExport').addEventListener('click',async()=>{await navigator.clipboard.writeText(exportText());announce('Demo JSON copied.')});
  $('#importFile').closest('.file-field').insertAdjacentHTML('afterend','<label class="file-field">Or paste JSON<textarea id="importPaste" rows="6" spellcheck="false"></textarea></label>');
  function prepareImport(text){pendingImport=null;$('#applyImport').disabled=true;try{const payload=JSON.parse(text);store.validateImport(payload);pendingImport=payload;$('#importPreview').textContent=`Valid version ${payload.version}: ${Object.keys(payload.productOverrides).length} overrides, ${payload.demoProducts.length} demo products, ${payload.inquiries.length} inquiries.`;$('#applyImport').disabled=false}catch(error){$('#importPreview').textContent=`Import rejected: ${error.message}`}}
  $('#importFile').addEventListener('change',async event=>{const file=event.target.files[0];if(file)prepareImport(await file.text())});$('#importPaste').addEventListener('input',event=>prepareImport(event.target.value));
  $('#applyImport').addEventListener('click',event=>confirmAction('Apply imported demo data','Current demo state will be backed up in memory before this validated import is applied.',()=>{store.importState(pendingImport);pendingImport=null;$('#importFile').value='';$('#importPaste').value='';$('#applyImport').disabled=true;$('#importPreview').textContent='Import completed.';renderAll();announce('Validated demo import applied.')},event.currentTarget));
  $('#resetDemo').addEventListener('click',event=>confirmAction('Reset demo data','Remove only local overrides, demo products, inquiries and settings? The original products remain unchanged.',()=>{store.resetDemoData();pendingImport=null;renderAll();announce('Demo data reset. Original catalog preserved.')},event.currentTarget));
  function renderAll(){renderOverview();renderProducts();renderInquiries();syncInquiryFilters();renderSettings()}
  $('#previewProduct').insertAdjacentHTML('beforebegin','<button class="admin-button secondary" id="previewCard" type="button">Preview Card</button>');
  $('#previewCard').addEventListener('click',()=>{const data=editorData(),win=open('','_blank','noopener,noreferrer');if(!win){announce('Preview window was blocked.');return}win.document.write(`<!doctype html><title>Local demo preview</title><style>body{margin:0;padding:8vw;background:#eee9df;color:#171815;font-family:Arial}.card{max-width:430px;background:#f7f3ec;box-shadow:0 18px 45px #0002}.image{display:grid;aspect-ratio:4/3;place-items:center;background:#e3ddd2}.image img{max-width:88%;max-height:88%;object-fit:contain}.copy{padding:26px}small{color:#9b7a45;letter-spacing:.18em;text-transform:uppercase}h1{font:2.2rem Georgia;margin:.35em 0}.price{font:1.3rem Georgia}</style><p>Local demo preview</p><article class="card"><div class="image">${data.image?`<img src="${escapeHtml(data.image)}" alt="">`:'Image path required'}</div><div class="copy"><small>${escapeHtml(data.brand)}</small><h1>${escapeHtml(data.name||'Untitled product')}</h1><p class="price">${money(data.priceOnRequest?null:data.price)}</p><span>${escapeHtml(data.status)}</span></div></article>`);win.document.close()});
  if(isSession())showApp();else showLogin();
})();
