(function appointmentExperience(global){
  'use strict';const form=document.querySelector('#appointmentForm');if(!form)return;
  const key='lefusil_appointments_v1',products=global.LEFUSIL_PRODUCTS||[],params=new URLSearchParams(location.search),requested=params.get('product'),source=params.get('source')||'appointment',product=products.find(item=>item.slug===requested),locale=global.LEFUSIL_LOCALE?.current||'en';
  const price=item=>item&&Number(item.price)>0?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(item.price):'';
  form.elements.product.innerHTML='<option value="">No specific product</option>'+products.map(item=>`<option value="${item.slug}">${item.brand} — ${item.name}</option>`).join('');
  const summary=document.querySelector('#appointmentProduct');function renderContext(item){if(!item){summary.hidden=true;return}summary.hidden=false;summary.querySelector('img').src=item.image;summary.querySelector('img').alt=`${item.brand} ${item.name}`;summary.querySelector('[data-product-brand]').textContent=item.brand;summary.querySelector('[data-product-name]').textContent=item.name;summary.querySelector('[data-product-price]').textContent=price(item);form.elements.product.value=item.slug;}
  renderContext(product);form.elements.product.addEventListener('change',()=>renderContext(products.find(item=>item.slug===form.elements.product.value)));summary.querySelector('[data-remove-product]').addEventListener('click',()=>{form.elements.product.value='';renderContext(null)});
  const today=new Date();today.setHours(0,0,0,0);form.elements.preferredDate.min=today.toISOString().slice(0,10);const max=new Date(today);max.setDate(max.getDate()+global.LEFUSIL_SITE_CONFIG.appointment.maxAdvanceDays);form.elements.preferredDate.max=max.toISOString().slice(0,10);
  form.addEventListener('submit',event=>{
    event.preventDefault();if(form.dataset.submitting==='true')return;
    const rules={fullName:{required:true,max:100},preferredContact:{required:true},email:{email:true,max:254},phone:{phone:true,max:40},country:{max:80},preferredDate:{required:true,future:true,maxDays:global.LEFUSIL_SITE_CONFIG.appointment.maxAdvanceDays},timeWindow:{required:true},notes:{min:10,max:1500}};
    const errors=global.lefusilForms.requireContact(form,global.lefusilForms.errors(form,rules));if(!form.elements.consent.checked)errors.consent=global.lefusilI18n?.t('Consent is required.')||'Consent is required.';
    if(!global.lefusilForms.show(form,errors)){global.lefusilAnalytics?.track('appointment_failed',{locale,sourcePage:'appointment'});return;}
    form.dataset.submitting='true';const data=new FormData(form),id=`APT-${Date.now().toString(36).toUpperCase()}`,selected=products.find(item=>item.slug===data.get('product'));
    const record={id,createdAt:new Date().toISOString(),name:global.lefusilForms.clean(data.get('fullName'),100),email:global.lefusilForms.clean(data.get('email'),254).toLowerCase(),phone:global.lefusilForms.phone(data.get('phone')),preferredContact:global.lefusilForms.clean(data.get('preferredContact'),30),country:global.lefusilForms.clean(data.get('country'),80),preferredDate:data.get('preferredDate'),timeWindow:data.get('timeWindow'),productSlug:selected?.slug||'',productName:selected?`${selected.brand} ${selected.name}`:'',category:global.lefusilForms.clean(data.get('purpose'),100),message:global.lefusilForms.clean(data.get('notes'),1500),status:'New',source,sourcePage:'appointment',inquiryType:'private_viewing',locale,demo:true};
    try{const appointments=JSON.parse(localStorage.getItem(key)||'[]'),inquiries=JSON.parse(localStorage.getItem('lefusil_admin_inquiries')||'[]');appointments.unshift(record);inquiries.unshift(record);localStorage.setItem(key,JSON.stringify(appointments));localStorage.setItem('lefusil_admin_inquiries',JSON.stringify(inquiries));document.querySelector('#appointmentView').hidden=true;const success=document.querySelector('#appointmentSuccess');success.hidden=false;success.querySelector('[data-reference]').textContent=id;success.focus();global.lefusilAnalytics?.track('appointment_submitted',{productSlug:record.productSlug,locale,sourcePage:'appointment'});}
    catch{form.dataset.submitting='false';document.querySelector('#appointmentStatus').textContent='Local demo storage is unavailable. Please try the contact form.';}
  });
  global.lefusilAnalytics?.track('appointment_started',{productSlug:product?.slug||'',locale,sourcePage:'appointment'});
})(window);
