(function imageSources(){
  const escape=(value)=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const optimized=(source,width)=>{const parts=String(source).split('/');const file=parts.pop();const stem=file.replace(/\.[^.]+$/,'');return `${parts.join('/')}/optimized/${stem}-${width}.webp`};
  const cardSizes='(max-width: 560px) calc(100vw - 48px), (max-width: 800px) calc(50vw - 30px), (max-width: 1100px) calc(50vw - 48px), min(28vw, 410px)';
  window.lefusilImages={
    optimized,
    card(source,alt,options={}){if(!source)return'';const loading=options.loading||'lazy';return `<picture><source type="image/webp" srcset="${escape(optimized(source,640))} 640w" sizes="${cardSizes}"><img src="${escape(source)}" alt="${escape(alt)}" loading="${loading}" decoding="async" onerror="this.hidden=true"></picture>`},
    thumb(source){if(!source)return'';return `<picture><source type="image/webp" srcset="${escape(optimized(source,640))}"><img src="${escape(source)}" alt="" loading="lazy" decoding="async" onerror="this.hidden=true"></picture>`}
  };
})();

(function buildGlobalComponents(){
  const path=(location.pathname.split('/').pop()||'index.html').toLowerCase();
  const current=path==='product.html'?'shop.html':path;
  const active=page=>current===page?' class="active" aria-current="page"':'';
  const icon=(name)=>({
    search:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m15.5 15.5 5 5"/></svg>',
    heart:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.8 4.7a5.5 5.5 0 0 0-7.8 0L12 5.8l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8l1.1 1.1L12 21l7.8-7.4 1.1-1.1a5.5 5.5 0 0 0-.1-7.8Z"/></svg>',
    menu:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 6.5h16M4 12h16M4 17.5h16"/></svg>',
    close:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m5 5 14 14M19 5 5 19"/></svg>'
  }[name]);

  const header=`<header class="header"><div class="container nav"><a class="brand" href="index.html" aria-label="LE FUSIL home"><strong>LE FUSIL</strong><small>Hunting &amp; Sporting Heritage</small></a><nav class="nav-links" aria-label="Primary"><a href="index.html"${active('index.html')}>Home</a><a href="shop.html"${active('shop.html')}>Collection</a><a href="index.html#brandGrid">Houses</a><a href="about.html"${active('about.html')}>About</a><a href="contact.html"${active('contact.html')}>Visit</a></nav><div class="header-actions"><button class="lang" type="button" data-ar>EN / AR</button><button class="icon-btn" type="button" data-search aria-label="Search collection">${icon('search')}</button><a class="icon-btn shortlist-link" href="favorites.html" aria-label="View saved pieces">${icon('heart')}<span class="shortlist-count" data-shortlist-count hidden>0</span></a><a class="btn header-cta" href="appointment.html">Book a Viewing</a><button class="icon-btn hamb" type="button" data-menu aria-label="Open menu" aria-controls="mobileMenu" aria-expanded="false">${icon('menu')}</button></div></div></header>`;

  const overlays=`<div class="overlay mobile-menu" id="mobileMenu" aria-hidden="true"><div class="mobile-menu-panel"><div class="mobile-menu-head"><a class="brand" href="index.html"><strong>LE FUSIL</strong><small>Hunting &amp; Sporting Heritage</small></a><div class="mobile-menu-head-actions"><button class="lang" type="button" data-ar>EN / AR</button><button class="icon-btn overlay-close" type="button" data-close aria-label="Close menu">${icon('close')}</button></div></div><nav aria-label="Mobile primary"><a href="index.html"${active('index.html')}>Home</a><a href="shop.html"${active('shop.html')}>Collection</a><a href="index.html#brandGrid">Selected Houses</a><a href="contact.html"${active('contact.html')}>Visit LE FUSIL</a></nav><div class="mobile-menu-foot"><a class="mobile-contact-link" href="contact.html">Contact the Store <span aria-hidden="true">→</span></a><p>Personal guidance and collection viewing inside the LE FUSIL showroom.</p><nav class="mobile-menu-social" aria-label="Follow Us"><span>Follow Us</span><div><a href="https://www.instagram.com/lefusil?igsh=MTE2c2Y2aXd2b3hyYg==" target="_blank" rel="noopener noreferrer" aria-label="LE FUSIL on Instagram"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4.25"/><circle cx="17.4" cy="6.7" r="1"/></svg></a><a href="https://www.facebook.com/share/19Ghff6xDV/" target="_blank" rel="noopener noreferrer" aria-label="LE FUSIL on Facebook"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14.3 21v-8h2.8l.4-3.2h-3.2V7.7c0-.9.3-1.6 1.7-1.6h1.7V3.2c-.3 0-1.3-.2-2.5-.2-2.5 0-4.2 1.5-4.2 4.4v2.4H8.2V13H11v8h3.3Z"/></svg></a></div></nav></div></div></div><div class="overlay" id="searchOverlay" aria-hidden="true"><button class="icon-btn overlay-close" type="button" data-close aria-label="Close search">${icon('close')}</button><div class="overlay-inner"><div class="eyebrow">Search the collection</div><label class="sr-only" for="globalSearch">Search</label><input class="search-input" id="globalSearch" placeholder="Name, brand or category" autocomplete="off"><div class="search-results" id="searchResults"></div></div></div><div class="overlay modal" id="ageModal" aria-hidden="true" role="dialog" aria-modal="true" aria-labelledby="ageTitle"><div class="modal-card"><div class="eyebrow">LE FUSIL</div><h2 id="ageTitle">Responsible Access</h2><p>This website presents hunting and sporting equipment for informational purposes. Regulated products are available only through lawful in-store procedures and required verification.</p><div class="actions"><button class="btn" type="button" id="enterSite">Enter Website</button><button class="btn btn-outline" type="button" id="leaveSite">Leave</button></div></div></div><div class="toast" id="toast" role="status" aria-live="polite"></div>`;

  const isHome=document.body.classList.contains('home-page');
  const footerLead=isHome?'':`<div class="footer-lead"><div><div class="eyebrow">The LE FUSIL Showroom</div><h2>Discover the collection with personal guidance.</h2></div><a class="btn" href="contact.html">Request a Private Viewing</a></div>`;
  const homeSocial=isHome?`<nav class="home-social" aria-label="LE FUSIL social media"><span class="home-social-label">Follow LE FUSIL</span><span class="home-social-links"><a href="https://www.instagram.com/lefusil?igsh=MTE2c2Y2aXd2b3hyYg==" target="_blank" rel="noopener noreferrer" aria-label="LE FUSIL on Instagram"><svg class="social-instagram" viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4.25"/><circle class="social-dot" cx="17.4" cy="6.7" r="1"/></svg></a><a href="https://www.facebook.com/share/19Ghff6xDV/" target="_blank" rel="noopener noreferrer" aria-label="LE FUSIL on Facebook"><svg class="social-facebook" viewBox="0 0 24 24" aria-hidden="true"><path d="M14.3 21v-8h2.8l.4-3.2h-3.2V7.7c0-.9.3-1.6 1.7-1.6h1.7V3.2c-.3 0-1.3-.2-2.5-.2-2.5 0-4.2 1.5-4.2 4.4v2.4H8.2V13H11v8h3.3Z"/></svg></a></span></nav>`:'';
  const footer=`<div class="legal-strip">Availability and transfer are subject to applicable Lebanese laws, licensing requirements and in-store verification.</div>${homeSocial}<footer class="footer"><div class="container">${footerLead}<div class="footer-grid"><div class="footer-brand"><h3>LE FUSIL</h3><p>A considered destination for hunting, sporting and outdoor equipment, presented through personal showroom service.</p></div><div><h4>Collection</h4><a href="shop.html">All Pieces</a><a href="shop.html?featured=true">Signature Selection</a><a href="shop.html?category=Double-Barrel">Double-Barrel</a><a href="shop.html?category=Ammunition">Ammunition</a></div><div><h4>Information</h4><a href="about.html">About LE FUSIL</a><a href="shop.html">Explore the Collection</a><a href="contact.html">Request Availability</a></div><div><h4>Visit</h4><a href="contact.html">Visit the Showroom</a><a href="contact.html">Private Viewing</a><a href="contact.html">Contact the Store</a></div><div><h4>Contact</h4><a href="contact.html">Begin an Inquiry</a><button type="button" class="footer-text-button" data-toast="Responsible access information is shown when you first enter the site.">Responsible Access</button></div></div><div class="footer-bottom"><span>© <span data-year></span> LE FUSIL. Concept presentation.</span><nav aria-label="Footer"><a href="index.html">Home</a><a href="shop.html">Collection</a><a href="contact.html">Contact</a></nav></div></div></footer>`;

  document.querySelector('#siteHeader').innerHTML=header;
  document.querySelector('#siteFooter').innerHTML=footer;
  if(!document.querySelector('link[href*="footer-accordion.css"]'))document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="css/footer-accordion.css?v=20260804-3">');
  addEventListener('DOMContentLoaded',()=>import('./footer-accordion.js?v=20260804-3'),{once:true});
  document.body.insertAdjacentHTML('beforeend',overlays);
})();
