(function buildGlobalComponents(){
  const path=(location.pathname.split('/').pop()||'index.html').toLowerCase();
  const current=path==='product.html'?'shop.html':path;
  const active=page=>current===page?' class="active" aria-current="page"':'';
  const icon=(name)=>({
    search:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m15.5 15.5 5 5"/></svg>',
    heart:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.8 4.7a5.5 5.5 0 0 0-7.8 0L12 5.8l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8l1.1 1.1L12 21l7.8-7.4 1.1-1.1a5.5 5.5 0 0 0-.1-7.8Z"/></svg>',
    menu:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 6.5h16M4 12h16M4 17.5h16"/></svg>',
    close:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m5 5 14 14M19 5 5 19"/></svg>'
  }[name]);

  const header=`<header class="header"><div class="container nav"><a class="brand" href="index.html" aria-label="LE FUSIL home"><strong>LE FUSIL</strong><small>Hunting &amp; Sporting Heritage</small></a><nav class="nav-links" aria-label="Primary"><a href="index.html"${active('index.html')}>Home</a><a href="shop.html"${active('shop.html')}>Collection</a><a href="index.html#brandGrid">Houses</a><a href="about.html"${active('about.html')}>About</a><a href="contact.html"${active('contact.html')}>Visit</a></nav><div class="header-actions"><button class="icon-btn" type="button" data-search aria-label="Search collection">${icon('search')}</button><a class="icon-btn shortlist-link" href="shop.html" aria-label="View shortlisted pieces">${icon('heart')}<span class="shortlist-count" data-shortlist-count hidden>0</span></a><button class="lang" type="button" data-ar>EN / AR</button><a class="btn header-cta" href="contact.html">Visit LE FUSIL</a><button class="icon-btn hamb" type="button" data-menu aria-label="Open menu" aria-controls="mobileMenu" aria-expanded="false">${icon('menu')}</button></div></div></header>`;

  const overlays=`<div class="overlay mobile-menu" id="mobileMenu" aria-hidden="true"><div class="mobile-menu-panel"><div class="mobile-menu-head"><a class="brand" href="index.html"><strong>LE FUSIL</strong><small>Hunting &amp; Sporting Heritage</small></a><button class="icon-btn overlay-close" type="button" data-close aria-label="Close menu">${icon('close')}</button></div><nav aria-label="Mobile primary"><a href="index.html"${active('index.html')}>Home</a><a href="shop.html"${active('shop.html')}>Collection</a><a href="index.html#brandGrid">Selected Houses</a><a href="about.html"${active('about.html')}>About</a><a href="contact.html"${active('contact.html')}>Visit LE FUSIL</a></nav><div class="mobile-menu-foot"><a class="btn" href="contact.html">Request a Private Viewing</a><a class="mobile-contact-link" href="contact.html">Contact the Store <span aria-hidden="true">→</span></a><p>Personal guidance and collection viewing inside the LE FUSIL showroom.</p><button class="lang" type="button" data-ar>EN / AR</button></div></div></div><div class="overlay" id="searchOverlay" aria-hidden="true"><button class="icon-btn overlay-close" type="button" data-close aria-label="Close search">${icon('close')}</button><div class="overlay-inner"><div class="eyebrow">Search the collection</div><label class="sr-only" for="globalSearch">Search</label><input class="search-input" id="globalSearch" placeholder="Name, brand or category" autocomplete="off"><div class="search-results" id="searchResults"></div></div></div><div class="overlay modal" id="ageModal" aria-hidden="true" role="dialog" aria-modal="true" aria-labelledby="ageTitle"><div class="modal-card"><div class="eyebrow">LE FUSIL</div><h2 id="ageTitle">Responsible Access</h2><p>This website presents hunting and sporting equipment for informational purposes. Regulated products are available only through lawful in-store procedures and required verification.</p><div class="actions"><button class="btn" type="button" id="enterSite">Enter Website</button><button class="btn btn-outline" type="button" id="leaveSite">Leave</button></div></div></div><div class="toast" id="toast" role="status" aria-live="polite"></div>`;

  const footer=`<div class="legal-strip">Availability and transfer are subject to applicable Lebanese laws, licensing requirements and in-store verification.</div><footer class="footer"><div class="container"><div class="footer-lead"><div><div class="eyebrow">The LE FUSIL Showroom</div><h2>Discover the collection with personal guidance.</h2></div><a class="btn" href="contact.html">Request a Private Viewing</a></div><div class="footer-grid"><div class="footer-brand"><h3>LE FUSIL</h3><p>A considered destination for hunting, sporting and outdoor equipment, presented through personal showroom service.</p></div><div><h4>Collection</h4><a href="shop.html">All Pieces</a><a href="shop.html?featured=true">Signature Selection</a><a href="shop.html?category=Double-Barrel">Double-Barrel</a><a href="shop.html?category=Ammunition">Ammunition</a></div><div><h4>Information</h4><a href="about.html">About LE FUSIL</a><a href="shop.html">Explore the Collection</a><a href="contact.html">Request Availability</a></div><div><h4>Visit</h4><a href="contact.html">Visit the Showroom</a><a href="contact.html">Private Viewing</a><a href="contact.html">Contact the Store</a></div><div><h4>Contact</h4><a href="contact.html">Begin an Inquiry</a><button type="button" class="footer-text-button" data-toast="Responsible access information is shown when you first enter the site.">Responsible Access</button></div></div><div class="footer-bottom"><span>© <span data-year></span> LE FUSIL. Concept presentation.</span><nav aria-label="Footer"><a href="index.html">Home</a><a href="shop.html">Collection</a><a href="contact.html">Contact</a></nav></div></div></footer>`;

  document.querySelector('#siteHeader').innerHTML=header;
  document.querySelector('#siteFooter').innerHTML=footer;
  document.body.insertAdjacentHTML('beforeend',overlays);
})();
