(function(){
 const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
 const products=window.LEFUSIL_PRODUCTS||[]; let lastFocus;
 function toast(message){const t=$('#toast');if(!t)return;t.textContent=message;t.classList.add('show');clearTimeout(t.timer);t.timer=setTimeout(()=>t.classList.remove('show'),3200)}
 function setOverlay(el,open){if(!el)return;el.classList.toggle('open',open);el.setAttribute('aria-hidden',String(!open));document.body.classList.toggle('lock',open);if(el.id==='mobileMenu')$$('[data-menu]').forEach(button=>{button.setAttribute('aria-expanded',String(open));button.setAttribute('aria-label',open?'Close menu':'Open menu')});if(open){lastFocus=document.activeElement;setTimeout(()=>$(el.id==='mobileMenu'?'[data-close]':'input,button,a',el)?.focus(),30)}else lastFocus?.focus()}
 function trap(e,el){if(e.key!=='Tab')return;const f=$$('a,button,input,select,textarea,[tabindex]:not([tabindex="-1"])',el).filter(x=>!x.disabled);if(!f.length)return;const first=f[0],last=f[f.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}
 const header=$('.header');addEventListener('scroll',()=>header?.classList.toggle('scrolled',scrollY>30),{passive:true});
 const menu=$('#mobileMenu'), search=$('#searchOverlay');$$('[data-menu]').forEach(b=>b.addEventListener('click',()=>setOverlay(menu,!menu.classList.contains('open'))));$$('[data-search]').forEach(b=>b.addEventListener('click',()=>{setOverlay(search,true);renderSearch('')}));$$('[data-close]').forEach(b=>b.addEventListener('click',()=>setOverlay(b.closest('.overlay'),false)));$$('#mobileMenu a').forEach(link=>link.addEventListener('click',()=>setOverlay(menu,false)));
 const searchInput=$('#globalSearch');function renderSearch(q){const list=$('#searchResults');if(!list)return;const found=products.filter(p=>(p.name+' '+p.brand+' '+p.category).toLowerCase().includes(q.toLowerCase()));list.innerHTML=found.length?found.map(p=>`<a class="search-result" href="product.html?slug=${p.slug}"><span>${p.brand} — ${p.name}</span><span>${p.category}</span></a>`).join(''):'<p>No items match your search.</p>'}searchInput?.addEventListener('input',e=>renderSearch(e.target.value));
 document.addEventListener('keydown',e=>{const open=$('.overlay.open');if(e.key==='Escape'&&open)setOverlay(open,false);if(open)trap(e,open)});
 if(!localStorage.getItem('lefusil_age_notice'))setOverlay($('#ageModal'),true);$('#enterSite')?.addEventListener('click',()=>{localStorage.setItem('lefusil_age_notice','accepted');setOverlay($('#ageModal'),false)});$('#leaveSite')?.addEventListener('click',()=>{location.href='about:blank'});
 $$('[data-ar]').forEach(b=>b.addEventListener('click',()=>toast('Arabic version is being prepared.')));
 const shortlist=()=>{try{return JSON.parse(localStorage.getItem('lefusil_shortlist')||'[]')}catch{return[]}};const syncShortlistCounter=()=>{$$('[data-shortlist-count]').forEach(counter=>{const count=shortlist().length;counter.textContent=count;counter.hidden=count===0})};window.toggleShortlist=id=>{const s=shortlist(),n=s.includes(id)?s.filter(x=>x!==id):[...s,id];localStorage.setItem('lefusil_shortlist',JSON.stringify(n));$$(`[data-shortlist="${id}"]`).forEach(b=>b.classList.toggle('active',n.includes(id)));syncShortlistCounter();toast(n.includes(id)?'Added to your shortlist.':'Removed from your shortlist.')};window.syncShortlist=()=>{$$('[data-shortlist]').forEach(b=>{const id=Number(b.dataset.shortlist);b.classList.toggle('active',shortlist().includes(id));if(!b.dataset.shortlistBound){b.dataset.shortlistBound='true';b.addEventListener('click',()=>window.toggleShortlist(id))}});syncShortlistCounter()};syncShortlistCounter();
 $$('[data-toast]').forEach(b=>b.addEventListener('click',()=>toast(b.dataset.toast)));$$('[data-year]').forEach(x=>x.textContent=new Date().getFullYear());
 const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.08});$$('.reveal').forEach(x=>io.observe(x));window.lefusilToast=toast;
})();
