(function(){
 const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
 window.LEFUSIL_ACCORDION=window.LEFUSIL_ACCORDION||(()=>{const reduced=matchMedia('(prefers-reduced-motion:reduce)'),animations=new WeakMap();let uid=0;const panelFor=trigger=>document.getElementById(trigger.getAttribute('aria-controls'));const finish=(trigger,panel,expanded)=>{const details=trigger.closest('details');trigger.setAttribute('aria-expanded',String(expanded));panel.hidden=!expanded;panel.inert=!expanded;panel.setAttribute('aria-hidden',String(!expanded));if(details)details.open=expanded;panel.style.removeProperty('height');panel.style.removeProperty('overflow');panel.style.removeProperty('opacity');panel.style.removeProperty('transform')};const set=(trigger,expanded,animate=true)=>{const panel=panelFor(trigger);if(!panel)return;const group=trigger.closest('[data-accordion-group]'),exclusive=!group?.dataset.accordionMedia||matchMedia(group.dataset.accordionMedia).matches;if(expanded&&group&&exclusive)group.querySelectorAll('[data-accordion-trigger][aria-expanded=true]').forEach(other=>{if(other!==trigger)set(other,false,animate)});animations.get(panel)?.cancel();trigger.setAttribute('aria-expanded',String(expanded));const details=trigger.closest('details'),start=panel.hidden?0:panel.getBoundingClientRect().height;if(expanded){if(details)details.open=true;panel.hidden=false;panel.inert=false;panel.setAttribute('aria-hidden','false')}if(!animate||reduced.matches||!panel.animate){finish(trigger,panel,expanded);return}panel.style.overflow='hidden';const animation=panel.animate([{height:`${start}px`,opacity:expanded?0:1,transform:expanded?'translateY(-4px)':'translateY(0)'},{height:`${expanded?panel.scrollHeight:0}px`,opacity:expanded?1:0,transform:expanded?'translateY(0)':'translateY(-4px)'}],{duration:220,easing:'cubic-bezier(.4, 0, .2, 1)'});animations.set(panel,animation);animation.onfinish=()=>{if(animations.get(panel)===animation){animations.delete(panel);finish(trigger,panel,expanded)}};animation.oncancel=()=>panel.style.removeProperty('overflow')};const prepare=(trigger,expanded=false)=>{const panel=panelFor(trigger);if(!panel)return;if(!panel.id)panel.id=`accordion-panel-${++uid}`;trigger.setAttribute('aria-controls',panel.id);trigger.setAttribute('aria-expanded',String(expanded));finish(trigger,panel,expanded)};document.addEventListener('click',event=>{const trigger=event.target.closest('[data-accordion-trigger]');if(!trigger)return;event.preventDefault();const group=trigger.closest('[data-accordion-group]');if(group?.dataset.accordionMedia&&!matchMedia(group.dataset.accordionMedia).matches){set(trigger,true,false);return}set(trigger,trigger.getAttribute('aria-expanded')!=='true')});return{set,prepare}})();
 dispatchEvent(new CustomEvent('lefusil:accordion-ready'));
 const products=window.LEFUSIL_PRODUCTS||[]; let lastFocus;
 function toast(message){const t=$('#toast');if(!t)return;t.textContent=message;t.classList.add('show');clearTimeout(t.timer);t.timer=setTimeout(()=>t.classList.remove('show'),3200)}
 function setOverlay(el,open){if(!el)return;el.classList.toggle('open',open);el.setAttribute('aria-hidden',String(!open));document.body.classList.toggle('lock',open);if(el.id==='mobileMenu')$$('[data-menu]').forEach(button=>{button.setAttribute('aria-expanded',String(open));button.setAttribute('aria-label',open?'Close menu':'Open menu')});if(open){lastFocus=document.activeElement;setTimeout(()=>$(el.id==='mobileMenu'?'[data-close]':'input,button,a',el)?.focus(),30)}else lastFocus?.focus()}
 function trap(e,el){if(e.key!=='Tab')return;const f=$$('a,button,input,select,textarea,[tabindex]:not([tabindex="-1"])',el).filter(x=>!x.disabled);if(!f.length)return;const first=f[0],last=f[f.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}
 const header=$('.header');addEventListener('scroll',()=>header?.classList.toggle('scrolled',scrollY>30),{passive:true});
 const menu=$('#mobileMenu'), search=$('#searchOverlay');$$('[data-menu]').forEach(b=>b.addEventListener('click',()=>setOverlay(menu,!menu.classList.contains('open'))));$$('[data-search]').forEach(b=>b.addEventListener('click',()=>{setOverlay(search,true);renderSearch('')}));$$('[data-close]').forEach(b=>b.addEventListener('click',()=>setOverlay(b.closest('.overlay'),false)));$$('#mobileMenu a').forEach(link=>link.addEventListener('click',()=>setOverlay(menu,false)));
 const searchInput=$('#globalSearch');function renderSearch(q){const list=$('#searchResults');if(!list)return;const found=products.filter(p=>(p.name+' '+p.brand+' '+p.category).toLowerCase().includes(q.toLowerCase()));list.innerHTML=found.length?found.map(p=>`<a class="search-result" href="product.html?slug=${p.slug}"><span>${p.brand} — ${p.name}</span><span>${p.category}</span></a>`).join(''):'<p>No items match your search.</p>'}searchInput?.addEventListener('input',e=>renderSearch(e.target.value));
 document.addEventListener('keydown',e=>{const open=$('.overlay.open');if(e.key==='Escape'&&$('.language-menu.open'))return;if(e.key==='Escape'&&open)setOverlay(open,false);if(open)trap(e,open)});
 if(!localStorage.getItem('lefusil_age_notice'))setOverlay($('#ageModal'),true);$('#enterSite')?.addEventListener('click',()=>{localStorage.setItem('lefusil_age_notice','accepted');setOverlay($('#ageModal'),false)});$('#leaveSite')?.addEventListener('click',()=>{location.href='about:blank'});
 $$('[data-ar]').forEach(b=>b.addEventListener('click',()=>toast('Arabic version is being prepared.')));
 const shortlist=()=>{try{const saved=JSON.parse(localStorage.getItem('lefusil_shortlist')||'[]');return [...new Set((Array.isArray(saved)?saved:[]).map(Number).filter(Number.isFinite))]}catch{return[]}};const setShortlistState=(button,active)=>{button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))};const syncShortlistCounter=()=>{$$('[data-shortlist-count]').forEach(counter=>{const count=shortlist().length;counter.textContent=count;counter.hidden=count===0})};window.toggleShortlist=id=>{const productId=Number(id),s=shortlist(),n=s.includes(productId)?s.filter(x=>x!==productId):[...s,productId];localStorage.setItem('lefusil_shortlist',JSON.stringify(n));$$(`[data-shortlist="${productId}"]`).forEach(button=>setShortlistState(button,n.includes(productId)));syncShortlistCounter();dispatchEvent(new CustomEvent('lefusil:shortlist',{detail:{ids:n}}));toast(n.includes(productId)?'Added to your shortlist.':'Removed from your shortlist.')};window.syncShortlist=()=>{$$('[data-shortlist]').forEach(button=>{const id=Number(button.dataset.shortlist);setShortlistState(button,shortlist().includes(id));if(!button.dataset.shortlistBound){button.dataset.shortlistBound='true';button.addEventListener('click',()=>window.toggleShortlist(id))}});syncShortlistCounter()};addEventListener('storage',event=>{if(event.key==='lefusil_shortlist')window.syncShortlist()});syncShortlistCounter();
const cardSelector='.product-card,.favorite-item',interactiveSelector='a,button,input,select,textarea,[role="button"]';const productLink=card=>card.querySelector('a[href*="product.html?slug="]');const prepareProductCard=card=>{const link=productLink(card);if(!link||card.dataset.cardLink)return;card.dataset.cardLink='true';card.tabIndex=0;card.setAttribute('aria-label',link.getAttribute('aria-label')||`View ${link.textContent.trim()}`)};const prepareProductCards=root=>{if(root.matches?.(cardSelector))prepareProductCard(root);root.querySelectorAll?.(cardSelector).forEach(prepareProductCard)};prepareProductCards(document);new MutationObserver(records=>records.forEach(record=>record.addedNodes.forEach(node=>{if(node.nodeType===1)prepareProductCards(node)}))).observe(document.body,{childList:true,subtree:true});document.addEventListener('click',event=>{const card=event.target.closest?.(cardSelector);if(!card||event.target.closest(interactiveSelector))return;const link=productLink(card);if(link)location.href=link.href});document.addEventListener('keydown',event=>{if(!['Enter',' '].includes(event.key)||event.target.matches(interactiveSelector))return;const card=event.target.closest?.(cardSelector);if(card&&event.target===card){event.preventDefault();productLink(card)?.click()}});
 $$('[data-toast]').forEach(b=>b.addEventListener('click',()=>toast(b.dataset.toast)));$$('[data-year]').forEach(x=>x.textContent=new Date().getFullYear());
 const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.08});$$('.reveal').forEach(x=>io.observe(x));window.lefusilToast=toast;
})();
