(function internationalization(global){
  'use strict';
  const locale=global.LEFUSIL_LOCALE?.current||'en',dictionary=global.LEFUSIL_TRANSLATIONS?.[locale]||{},translate=value=>dictionary[String(value).trim()]||value,supported=[...new Set(global.LEFUSIL_SITE_CONFIG.supportedLocales)].filter(Boolean);let switcherId=0;
  function switcher(){const id=`language-menu-${++switcherId}`;return`<div class="language-switcher"><button class="language-toggle" type="button" aria-expanded="false" aria-controls="${id}" aria-haspopup="menu" aria-label="Select language; current language ${global.LEFUSIL_SITE_CONFIG.localeLabels[locale]||locale}">${locale.toUpperCase()}</button><div class="language-menu" id="${id}" role="menu" aria-label="Languages">${supported.filter(code=>code!==locale).map(code=>`<button type="button" role="menuitem" data-locale="${code}">${global.LEFUSIL_SITE_CONFIG.localeLabels[code]||code.toUpperCase()}</button>`).join('')}</div></div>`}
  function enhance(){
    document.querySelectorAll('[data-ar]').forEach(node=>node.outerHTML=switcher());
    const appointmentActive=location.pathname.endsWith('appointment.html');
    document.querySelectorAll('.nav-links').forEach(nav=>{if(!nav.querySelector('a[href="appointment.html"]'))nav.insertAdjacentHTML('beforeend',`<a href="appointment.html" data-i18n="Appointment"${appointmentActive?' class="active" aria-current="page"':''}>Appointment</a>`)});
    document.querySelectorAll('.footer-grid').forEach(grid=>grid.insertAdjacentHTML('beforeend','<div><h4 data-i18n="Legal">Legal</h4><a href="privacy.html" data-i18n="Privacy">Privacy</a><a href="terms.html" data-i18n="Terms">Terms</a><a href="cookies.html" data-i18n="Cookies">Cookies</a><a href="legal-notice.html" data-i18n="Legal Notice">Legal Notice</a><a href="responsible-use.html" data-i18n="Responsible Use">Responsible Use</a><a href="appointment.html" data-i18n="Appointment">Appointment</a><button class="footer-text-button" type="button" data-consent-manage data-i18n="Cookie Settings">Cookie Settings</button></div>'));
    document.addEventListener('click',event=>{const toggle=event.target.closest('.language-toggle'),selector=event.target.closest('.language-switcher');document.querySelectorAll('.language-menu.open').forEach(menu=>{if(menu!==toggle?.nextElementSibling&&!selector?.contains(menu)){menu.classList.remove('open');menu.previousElementSibling.setAttribute('aria-expanded','false')}});if(toggle){const menu=document.getElementById(toggle.getAttribute('aria-controls')),open=!menu.classList.contains('open');document.querySelectorAll('.language-menu.open').forEach(other=>{if(other!==menu){other.classList.remove('open');other.previousElementSibling.setAttribute('aria-expanded','false')}});menu.classList.toggle('open',open);toggle.setAttribute('aria-expanded',String(open))}const choice=event.target.closest('[data-locale]');if(choice){const menu=choice.closest('.language-menu');menu?.classList.remove('open');menu?.previousElementSibling?.setAttribute('aria-expanded','false');global.LEFUSIL_LOCALE.set(choice.dataset.locale)}});
    document.addEventListener('keydown',event=>{if(event.key==='Escape')document.querySelectorAll('.language-menu.open').forEach(menu=>{menu.classList.remove('open');menu.previousElementSibling.setAttribute('aria-expanded','false');menu.previousElementSibling.focus()})});
  }
  function apply(root=document){root.querySelectorAll('[data-i18n]').forEach(node=>node.textContent=translate(node.dataset.i18n));const walker=document.createTreeWalker(root.body||root,NodeFilter.SHOW_TEXT);let node;while(node=walker.nextNode()){if(node.parentElement?.closest('script,style,code,[data-no-translate]'))continue;const raw=node.nodeValue,trim=raw.trim();if(trim&&dictionary[trim])node.nodeValue=raw.replace(trim,dictionary[trim])}root.querySelectorAll('[data-i18n-placeholder]').forEach(node=>node.placeholder=translate(node.dataset.i18nPlaceholder))}
  global.lefusilI18n={locale,t:translate,apply};addEventListener('DOMContentLoaded',()=>{enhance();apply()});
})(window);
