(function homepageCollections(){
  const products=window.LEFUSIL_PRODUCTS||[],locale=window.LEFUSIL_LOCALE?.current||'en',dictionary=window.LEFUSIL_TRANSLATIONS?.[locale]||{},translate=value=>dictionary[value]||value;
  const featuredGrid=document.querySelector('#featuredProducts');
  if(featuredGrid){featuredGrid.innerHTML=products.filter(product=>product.featured).slice(0,6).map(productCard).join('');syncShortlist()}
  const visibleProducts=products.filter(product=>product.visible!==false&&!['draft','archived','hidden'].includes(String(product.status||'').toLowerCase()));
  const countBy=key=>visibleProducts.reduce((map,product)=>{const value=String(product[key]||'').trim();if(value)map.set(value,(map.get(value)||0)+1);return map},new Map());
  const brandGrid=document.querySelector('#brandGrid');
  if(brandGrid){
    const counts=countBy('brand'),byName=new Map([...counts].map(([brand,count])=>[brand.toLocaleLowerCase('en'),{brand,count}])),configured=window.LEFUSIL_HOMEPAGE_CONFIG?.featuredMakers||[];
    const makers=[...new Set(configured.map(name=>String(name).trim().toLocaleLowerCase('en')).filter(Boolean))].map(name=>byName.get(name)).filter(item=>item?.count>0).slice(0,6);
    const countLabel=count=>`${new Intl.NumberFormat(locale).format(count)} ${translate(count===1?'piece':'pieces')}`,accessible=(brand,count)=>translate('View {count} {maker} pieces in the collection').replace('{count}',new Intl.NumberFormat(locale).format(count)).replace('{maker}',brand);
    brandGrid.innerHTML=makers.map(({brand,count},index)=>{const params=new URLSearchParams({brand,lang:locale});return`<a class="house-link reveal${index===0?' house-featured':''}" href="shop.html?${params}" aria-label="${accessible(brand,count)}"><span dir="ltr">${brand}</span><small>${countLabel(count)}</small><b aria-hidden="true">→</b></a>`}).join('');
    const all=document.querySelector('.houses-all-link');if(all){const params=new URLSearchParams({lang:locale});all.href=`shop.html?${params}`}
  }
  const descriptions={'Double-Barrel':'Classic sporting configurations with enduring balance and character.','Semi-Automatic':'Contemporary field and sporting pieces from established makers.','Air Rifle':'Precision air rifles selected for sporting consultation.','Single Shot':'Purposeful single-shot formats with direct handling.','Ammunition':'Current sporting ammunition, subject to in-store verification.','Pump-Action':'Practical sporting configurations available for personal consultation.'};
  const images={'Double-Barrel':'assets/images/products/gamba-bohler-steel-12/optimized/gamba-bohler-steel-12-01-original-1600.webp','Semi-Automatic':'assets/images/products/benelli-raffaello-lord-20/optimized/benelli-raffaello-lord-20-01-original-1600.webp','Air Rifle':'assets/images/products/puncher-nemesis/optimized/puncher-nemesis-01-original-1600.webp','Single Shot':'assets/images/products/falcon-srl-410/optimized/falcon-srl-410-01-original-1600.webp','Ammunition':'assets/images/products/west-trap-75/optimized/west-trap-75-01-original-1600.webp','Pump-Action':'assets/images/products/remington-pump-action/optimized/remington-pump-action-01-original-1600.webp'};
  const categories=[...countBy('category')].sort(([a],[b])=>{const order=['Double-Barrel','Semi-Automatic','Air Rifle','Single Shot','Pump-Action','Ammunition'];return order.indexOf(a)-order.indexOf(b)});
  const categoryGrid=document.querySelector('#categoryGrid');
  if(categoryGrid){categoryGrid.innerHTML=categories.map(([category,count],index)=>`<article class="category-editorial reveal"><img src="${images[category]||'assets/images/showroom/optimized/le-fusil-collection-wall-640.webp'}" alt="" loading="lazy" decoding="async"><span class="category-shade" aria-hidden="true"></span><div class="category-content"><span class="category-number">${String(index+1).padStart(2,'0')}</span><div class="category-count">${count} ${count===1?'piece':'pieces'}</div><h3>${category}</h3><p>${descriptions[category]||'Explore the current selection with personal showroom guidance.'}</p><a href="shop.html?category=${encodeURIComponent(category)}">Explore Collection <span aria-hidden="true">→</span></a></div></article>`).join('')}
  const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');revealObserver.unobserve(entry.target)}}),{threshold:.08});
  document.querySelectorAll('#brandGrid .reveal,#categoryGrid .reveal').forEach(element=>revealObserver.observe(element));
})();
function money(p){return Number(p.price)>0?new Intl.NumberFormat('en-US',{style:'currency',currency:p.currency||'USD',maximumFractionDigits:0}).format(Number(p.price)):'Price on request'}
function productCard(p){
  const name=String(p.name||'Product details on request'),brand=String(p.brand||'LE FUSIL'),category=String(p.category||''),spec=p.specifications||{},calibre=String(spec.Gauge||spec.Caliber||''),origin=String(spec.Origin||p.origin||''),slug=encodeURIComponent(p.slug||p.id||''),price=money(p),priceClass=Number(p.price)>0?'':' price-request',image=p.image||'',raw=String(p.availability||'').toLowerCase(),availability=raw.includes('unavailable')?['Currently unavailable','availability-unavailable']:raw.includes('limited')?['Limited','availability-limited']:raw==='available'||raw.includes('in stock')?['Available','availability-available']:['On request','availability-request'];
  const technical=[category,calibre,origin].filter(Boolean).slice(0,3);
  return `<article class="product-card"><div class="product-image"><span class="product-silhouette" aria-hidden="true"></span>${image?lefusilImages.card(image,`${brand} ${name}`):''}<button type="button" class="shortlist" data-shortlist="${p.id}" aria-label="Add ${brand} ${name} to shortlist"><svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M20.8 4.7a5.5 5.5 0 0 0-7.8 0L12 5.8l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8l1.1 1.1L12 21l7.8-7.4 1.1-1.1a5.5 5.5 0 0 0-.1-7.8Z"/></svg></button></div><div class="product-info"><div class="product-brand">${brand}</div><h3><a href="product.html?slug=${slug}">${name}</a></h3>${technical.length?`<div class="product-card-meta">${technical.map(value=>`<span>${value}</span>`).join('')}</div>`:''}<div class="product-buyline"><div class="price${priceClass}">${price}</div><span class="availability ${availability[1]}">${availability[0]}</span></div><div class="card-actions"><a class="card-primary" href="product.html?slug=${slug}">View Details</a><a class="card-secondary" href="contact.html?product=${slug}">Request Availability <span aria-hidden="true">→</span></a></div></div></article>`;
}
