begin;
create table public.inquiries (id uuid primary key default extensions.gen_random_uuid(), public_reference text not null unique default ('LF-'||upper(substr(replace(extensions.gen_random_uuid()::text,'-',''),1,12))), inquiry_type text not null check(inquiry_type in ('contact','product_availability','manual')), product_id uuid references public.products(id) on delete set null, customer_name text not null check(btrim(customer_name)<>''), email extensions.citext not null, phone text, preferred_contact text, country text, message text not null check(btrim(message)<>''), status text not null default 'new' check(status in ('new','contacted','appointment_scheduled','closed','archived')), source_page text, source_url text, consent_version text, archived_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), assigned_to uuid references public.profiles(id) on delete set null);
create table public.customers (id uuid primary key default extensions.gen_random_uuid(), normalized_email extensions.citext not null unique, display_email extensions.citext not null, name text not null, phone text, preferred_contact text, country text, status text not null default 'lead' check(status in ('lead','contacted','negotiating','interested','vip','sold','inactive','archived')), source text not null default 'inquiry', archived_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), last_activity_at timestamptz not null default now(), check(normalized_email=lower(btrim(normalized_email::text))));
create table public.customer_inquiries (customer_id uuid not null references public.customers(id) on delete cascade, inquiry_id uuid not null references public.inquiries(id) on delete restrict, linked_at timestamptz not null default now(), linked_by uuid references public.profiles(id) on delete set null, link_method text not null check(link_method in ('normalized_email','manual','import')), primary key(customer_id,inquiry_id));
create table public.customer_notes (id uuid primary key default extensions.gen_random_uuid(), customer_id uuid not null references public.customers(id) on delete cascade, note text not null check(btrim(note)<>''), created_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.tags (id uuid primary key default extensions.gen_random_uuid(), name text not null, normalized_name text not null unique check(normalized_name=lower(btrim(normalized_name))), created_at timestamptz not null default now(), created_by uuid references public.profiles(id) on delete set null);
create table public.customer_tags (customer_id uuid not null references public.customers(id) on delete cascade, tag_id uuid not null references public.tags(id) on delete restrict, created_at timestamptz not null default now(), created_by uuid references public.profiles(id) on delete set null, primary key(customer_id,tag_id));
create table public.customer_timeline (id uuid primary key default extensions.gen_random_uuid(), customer_id uuid not null references public.customers(id) on delete cascade, event_type text not null, safe_summary text not null, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), created_by uuid references public.profiles(id) on delete set null);
commit;
